export const LOAD_RESTAURANTS = 'LOAD_RESTAURANTS';
export const HANDLE_NAME_PROPS = 'HANDLE_NAME_PROPS';
export const HANDLE_LOCATION_PROPS = 'HANDLE_LOCATION_PROPS';
export const HANDLE_PRICE_RANGE_PROPS = 'HANDLE_PRICE_RANGE_PROPS';
